// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn1JiXB7Y1CH2oG7u93iljZ4iK0ixAnXM',
    appId: '1:826763887865:web:5d630ada0a6765753f8e28',
    messagingSenderId: '826763887865',
    projectId: 'nomu-47a92',
    authDomain: 'nomu-47a92.firebaseapp.com',
    storageBucket: 'nomu-47a92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALWBqG_U5NkdH5aR9VLds609e9qtObJNk',
    appId: '1:826763887865:android:dfbe45bcf4b175b73f8e28',
    messagingSenderId: '826763887865',
    projectId: 'nomu-47a92',
    storageBucket: 'nomu-47a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFdO5Rw5brnzpoyZ2uML1CMyq9ovhcpsI',
    appId: '1:826763887865:ios:689dda5f9b77fbfd3f8e28',
    messagingSenderId: '826763887865',
    projectId: 'nomu-47a92',
    storageBucket: 'nomu-47a92.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFdO5Rw5brnzpoyZ2uML1CMyq9ovhcpsI',
    appId: '1:826763887865:ios:689dda5f9b77fbfd3f8e28',
    messagingSenderId: '826763887865',
    projectId: 'nomu-47a92',
    storageBucket: 'nomu-47a92.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn1JiXB7Y1CH2oG7u93iljZ4iK0ixAnXM',
    appId: '1:826763887865:web:70dd11f695e7fa5e3f8e28',
    messagingSenderId: '826763887865',
    projectId: 'nomu-47a92',
    authDomain: 'nomu-47a92.firebaseapp.com',
    storageBucket: 'nomu-47a92.firebasestorage.app',
  );

}